# Generated by Django 2.2.6 on 2019-10-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0005_auto_20191029_0036'),
        ('project_module', '0003_auto_20191026_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='noticereceive',
            options={'verbose_name': '通知接收', 'verbose_name_plural': '通知接收'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': '项目参与关系', 'verbose_name_plural': '项目参与关系'},
        ),
        migrations.AlterModelOptions(
            name='participationrole',
            options={'verbose_name': '参与角色', 'verbose_name_plural': '参与角色'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AddField(
            model_name='project',
            name='first_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_task', to='task_module.Task', verbose_name='首位任务'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(blank=True, max_length=512, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='noticereceive',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.Notice', verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='noticereceive',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='阅读时间'),
        ),
        migrations.AlterField(
            model_name='noticereceive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='participationrole',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.Participation', verbose_name='参与关系'),
        ),
        migrations.AlterField(
            model_name='participationrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=48, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=8, verbose_name='角色名'),
        ),
    ]
