# Generated by Django 2.2.6 on 2019-10-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0004_auto_20191029_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_project', to='task_module.Task', verbose_name='首位任务'),
        ),
    ]
