# Generated by Django 2.2.6 on 2019-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, '阶段'), (1, '主任务'), (2, '子任务'), (3, '清单')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '未完成'), (4, '已暂停'), (5, '已取消'), (6, '其他')], default=0),
        ),
    ]
