# Generated by Django 2.2.6 on 2019-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0003_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '阶段'), (2, '主任务'), (3, '子任务'), (4, '清单')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已完成'), (4, '未完成'), (5, '已暂停'), (6, '已取消')], default=0),
        ),
    ]
