# Generated by Django 2.2.5 on 2019-10-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=12)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('education', models.PositiveSmallIntegerField(choices=[('HS', 'Highschool'), ('BD', 'Bachelordegree'), ('MD', 'Masterdegree'), ('DD', 'Doctoraldegree')], default=0)),
                ('duty', models.CharField(blank=True, max_length=16)),
                ('contact', models.CharField(blank=True, max_length=16)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[('OFL', 'Offline'), ('OL', 'Online'), ('BY', 'Busy'), ('WO', 'WO'), ('CK', 'CK')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='user_module.User')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='user_module.User')),
            ],
        ),
    ]
