# Generated by Django 2.2.6 on 2019-10-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0001_initial'),
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_module.Chat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '专科'), (4, '本科'), (5, '硕士'), (6, '博士'), (7, '其他')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '离线'), (1, '在线'), (2, '其他')], default=0),
        ),
    ]
