# Generated by Django 2.2.6 on 2019-10-25 18:37

from django.db import migrations, models
import django.db.models.deletion
import utils.model_manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_auto_20191016_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '好友关系', 'verbose_name_plural': '好友关系'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='friend',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='接受'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_module.Chat', verbose_name='聊天室'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='user_module.User', verbose_name='目标用户'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发起时间'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='user_module.User', verbose_name='发起用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_manager.PictureUpload('avatars'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=16, verbose_name='居住地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=16, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.CharField(blank=True, max_length=16, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '专科'), (5, '本科'), (6, '硕士'), (7, '博士'), (8, '其他')], default=0, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=128, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=12, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '离线'), (2, '在线'), (3, '其他')], default=0, verbose_name='登录状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, verbose_name='用户名'),
        ),
    ]
