# Generated by Django 2.2.6 on 2019-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_auto_20191026_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='性别'),
        ),
    ]
